'use client';

import Head from 'next/head'
import Image from 'next/image'
import { Poppins } from '@next/font/google'

import styles from '@/styles/Home.module.css'
import {Box, Grid, IconButton} from "@mui/material"
import {Instagram, WhatsApp, MailOutline} from '@mui/icons-material';
import Navbar from '@/components/Navbar'

import { ThemeProvider } from '@mui/material'
import theme from '@/styles/material'

const inter = Poppins({
  weight: '400',
  subsets: ['latin'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Ana Loredo Psicología</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
      <main className={ styles.main}> 
        <div className={inter.className}>
        <Box sx={{width:"100vw", height:"100vh"}}>
          <Navbar/>
          <Box className={styles.container}> 
            <div className={styles.titles}>
              <div className={styles.titleMain}>Ana</div>
              <div className={styles.titleMain}>Loredo</div>
              <div className={styles.titleSecondary}>Psigologa</div>
              <div>Puntitos</div>
            </div>
            <div className={styles.hero}>
              <Image
                src="/images/ana.png" // Route of the image file
                height={960} // Desired size with correct aspect ratio
                width={685.5} // Desired size with correct aspect ratio
                alt="Ana Loredo"
              />
            </div>
            <div className={styles.info}>
              <div>Decoracion</div>
              <div>Psicologa y rayita</div>
              <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent justo leo, interdum et aliquam sit amet, elementum eget sapien. Integer aliquet iaculis orci in tincidunt</div>
              <div>Info Plaza Fiesta San agustin</div>
            </div>
          </Box>
        </Box>

        <Box sx={{height:"100vh"}}>
          <div>Formulario</div>
        </Box>

        <Box>
          <div>Bottom</div>
        </Box>
        </div>
      </main>
      </ThemeProvider>
    </>
  )
}
